static void* Opcode[] =
{
	&&Opcode00, &&Opcode01, &&Opcode02, &&Opcode03, &&Opcode04, &&Opcode05, &&Opcode06, &&Opcode07, &&Opcode08, &&Opcode09, &&Opcode0A, &&Opcode0B, &&Opcode0C, &&Opcode0D, &&Opcode0E, &&Opcode0F,
	&&Opcode10, &&Opcode11, &&Opcode12, &&Opcode13, &&Opcode14, &&Opcode15, &&Opcode16, &&Opcode17, &&Opcode18, &&Opcode19, &&Opcode1A, &&Opcode1B, &&Opcode1C, &&Opcode1D, &&Opcode1E, &&Opcode1F,
	&&Opcode20, &&Opcode21, &&Opcode22, &&Opcode23, &&Opcode24, &&Opcode25, &&Opcode26, &&Opcode27, &&Opcode28, &&Opcode29, &&Opcode2A, &&Opcode2B, &&Opcode2C, &&Opcode2D, &&Opcode2E, &&Opcode2F,
	&&Opcode30, &&Opcode31, &&Opcode32, &&Opcode33, &&Opcode34, &&Opcode35, &&Opcode36, &&Opcode37, &&Opcode38, &&Opcode39, &&Opcode3A, &&Opcode3B, &&Opcode3C, &&Opcode3D, &&Opcode3E, &&Opcode3F,
	&&Opcode40, &&Opcode41, &&Opcode42, &&Opcode43, &&Opcode44, &&Opcode45, &&Opcode46, &&Opcode47, &&Opcode48, &&Opcode49, &&Opcode4A, &&Opcode4B, &&Opcode4C, &&Opcode4D, &&Opcode4E, &&Opcode4F,
	&&Opcode50, &&Opcode51, &&Opcode52, &&Opcode53, &&Opcode54, &&Opcode55, &&Opcode56, &&Opcode57, &&Opcode58, &&Opcode59, &&Opcode5A, &&Opcode5B, &&Opcode5C, &&Opcode5D, &&Opcode5E, &&Opcode5F,
	&&Opcode60, &&Opcode61, &&Opcode62, &&Opcode63, &&Opcode64, &&Opcode65, &&Opcode66, &&Opcode67, &&Opcode68, &&Opcode69, &&Opcode6A, &&Opcode6B, &&Opcode6C, &&Opcode6D, &&Opcode6E, &&Opcode6F,
	&&Opcode70, &&Opcode71, &&Opcode72, &&Opcode73, &&Opcode74, &&Opcode75, &&Opcode76, &&Opcode77, &&Opcode78, &&Opcode79, &&Opcode7A, &&Opcode7B, &&Opcode7C, &&Opcode7D, &&Opcode7E, &&Opcode7F,
	&&Opcode80, &&Opcode81, &&Opcode82, &&Opcode83, &&Opcode84, &&Opcode85, &&Opcode86, &&Opcode87, &&Opcode88, &&Opcode89, &&Opcode8A, &&Opcode8B, &&Opcode8C, &&Opcode8D, &&Opcode8E, &&Opcode8F,
	&&Opcode90, &&Opcode91, &&Opcode92, &&Opcode93, &&Opcode94, &&Opcode95, &&Opcode96, &&Opcode97, &&Opcode98, &&Opcode99, &&Opcode9A, &&Opcode9B, &&Opcode9C, &&Opcode9D, &&Opcode9E, &&Opcode9F,
	&&OpcodeA0, &&OpcodeA1, &&OpcodeA2, &&OpcodeA3, &&OpcodeA4, &&OpcodeA5, &&OpcodeA6, &&OpcodeA7, &&OpcodeA8, &&OpcodeA9, &&OpcodeAA, &&OpcodeAB, &&OpcodeAC, &&OpcodeAD, &&OpcodeAE, &&OpcodeAF,
	&&OpcodeB0, &&OpcodeB1, &&OpcodeB2, &&OpcodeB3, &&OpcodeB4, &&OpcodeB5, &&OpcodeB6, &&OpcodeB7, &&OpcodeB8, &&OpcodeB9, &&OpcodeBA, &&OpcodeBB, &&OpcodeBC, &&OpcodeBD, &&OpcodeBE, &&OpcodeBF,
	&&OpcodeC0, &&OpcodeC1, &&OpcodeC2, &&OpcodeC3, &&OpcodeC4, &&OpcodeC5, &&OpcodeC6, &&OpcodeC7, &&OpcodeC8, &&OpcodeC9, &&OpcodeCA, &&OpcodeCB, &&OpcodeCC, &&OpcodeCD, &&OpcodeCE, &&OpcodeCF,
	&&OpcodeD0, &&OpcodeD1, &&OpcodeD2, &&OpcodeD3, &&OpcodeD4, &&OpcodeD5, &&OpcodeD6, &&OpcodeD7, &&OpcodeD8, &&OpcodeD9, &&OpcodeDA, &&OpcodeDB, &&OpcodeDC, &&OpcodeDD, &&OpcodeDE, &&OpcodeDF,
	&&OpcodeE0, &&OpcodeE1, &&OpcodeE2, &&OpcodeE3, &&OpcodeE4, &&OpcodeE5, &&OpcodeE6, &&OpcodeE7, &&OpcodeE8, &&OpcodeE9, &&OpcodeEA, &&OpcodeEB, &&OpcodeEC, &&OpcodeED, &&OpcodeEE, &&OpcodeEF,
	&&OpcodeF0, &&OpcodeF1, &&OpcodeF2, &&OpcodeF3, &&OpcodeF4, &&OpcodeF5, &&OpcodeF6, &&OpcodeF7, &&OpcodeF8, &&OpcodeF9, &&OpcodeFA, &&OpcodeFB, &&OpcodeFC, &&OpcodeFD, &&OpcodeFE, &&OpcodeFF
};


void Processor_CPU_Run()
{
    CPU.TargetCycle = Graphics_PPU_Next_VBlank_Cycle();

	goto *Opcode[Memory_CPU_Read(CPU.PC)];

	Opcode00:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	BRK();							CPU.CycleCount += 7;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode01:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ORA(Indexed_Indirect());		CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode02:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	KIL();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode03:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SLO(Indexed_Indirect());		CPU.CycleCount += 8;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode04:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode05:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ORA(Zero_Page());				CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode06:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ASL(Zero_Page());				CPU.CycleCount += 5;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode07:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SLO(Zero_Page());				CPU.CycleCount += 5;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode08:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	PHP();							CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode09:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ORA(Immediate());				CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode0A:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ASL_Accumulator();        		CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode0B:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ANC(Immediate());				CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode0C:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode0D:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ORA(Absolute());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode0E:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ASL(Absolute());				CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode0F:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SLO(Absolute());				CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode10:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	BPL(Relative());				CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode11:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ORA(Indirect_Indexed_Read());	CPU.CycleCount += 5;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode12:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	KIL();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode13:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SLO(Indirect_Indexed());		CPU.CycleCount += 8;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode14:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode15:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ORA(Zero_Page_X());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode16:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ASL(Zero_Page_X());				CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode17:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SLO(Zero_Page_X());				CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode18:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	CLC();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode19:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ORA(Absolute_Y_Read());			CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode1A:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode1B:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SLO(Absolute_Y());				CPU.CycleCount += 7;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode1C:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode1D:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ORA(Absolute_X_Read());			CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode1E:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ASL(Absolute_X());				CPU.CycleCount += 7;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode1F:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SLO(Absolute_X());				CPU.CycleCount += 7;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode20:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	JSR(Absolute());				CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode21:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	AND(Indexed_Indirect());		CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode22:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	KIL();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode23:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	RLA(Indexed_Indirect());		CPU.CycleCount += 8;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode24:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	BIT(Zero_Page());				CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode25:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	AND(Zero_Page());				CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode26:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ROL(Zero_Page());				CPU.CycleCount += 5;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode27:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	RLA(Zero_Page());				CPU.CycleCount += 5;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode28:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	PLP();							CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode29:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	AND(Immediate());				CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode2A:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ROL_Accumulator();        		CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode2B:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ANC(Immediate());				CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode2C:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	BIT(Absolute());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode2D:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	AND(Absolute());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode2E:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ROL(Absolute());				CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode2F:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	RLA(Absolute());				CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode30:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	BMI(Relative());				CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode31:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	AND(Indirect_Indexed_Read());	CPU.CycleCount += 5;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode32:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	KIL();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode33:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	RLA(Indirect_Indexed());		CPU.CycleCount += 8;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode34:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode35:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	AND(Zero_Page_X());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode36:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ROL(Zero_Page_X());				CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode37:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	RLA(Zero_Page_X());				CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode38:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SEC();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode39:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	AND(Absolute_Y_Read());			CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode3A:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode3B:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	RLA(Absolute_Y());				CPU.CycleCount += 7;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode3C:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode3D:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	AND(Absolute_X_Read());			CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode3E:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ROL(Absolute_X());				CPU.CycleCount += 7;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode3F:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	RLA(Absolute_X());				CPU.CycleCount += 7;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode40:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	RTI();							CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode41:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	EOR(Indexed_Indirect());		CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode42:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	KIL();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode43:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SRE(Indexed_Indirect());		CPU.CycleCount += 8;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode44:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode45:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	EOR(Zero_Page());				CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode46:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LSR(Zero_Page());				CPU.CycleCount += 5;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode47:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SRE(Zero_Page());				CPU.CycleCount += 5;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode48:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	PHA();							CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode49:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	EOR(Immediate());				CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode4A:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LSR_Accumulator();        		CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode4B:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ALR(Immediate());				CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode4C:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	JMP(Absolute());				CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode4D:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	EOR(Absolute());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode4E:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LSR(Absolute());				CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode4F:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SRE(Absolute());				CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode50:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	BVC(Relative());				CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode51:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	EOR(Indirect_Indexed_Read());	CPU.CycleCount += 5;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode52:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	KIL();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode53:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SRE(Indirect_Indexed());		CPU.CycleCount += 8;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode54:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode55:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	EOR(Zero_Page_X());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode56:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LSR(Zero_Page_X());				CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode57:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SRE(Zero_Page_X());				CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode58:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	CLI();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode59:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	EOR(Absolute_Y_Read());			CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode5A:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode5B:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SRE(Absolute_Y());				CPU.CycleCount += 7;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode5C:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode5D:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	EOR(Absolute_X_Read());			CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode5E:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LSR(Absolute_X());				CPU.CycleCount += 7;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode5F:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SRE(Absolute_X());				CPU.CycleCount += 7;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode60:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	RTS();							CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode61:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ADC(Indexed_Indirect());		CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode62:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	KIL();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode63:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	RRA(Indexed_Indirect());		CPU.CycleCount += 8;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode64:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode65:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ADC(Zero_Page());				CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode66:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ROR(Zero_Page());				CPU.CycleCount += 5;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode67:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	RRA(Zero_Page());				CPU.CycleCount += 5;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode68:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	PLA();							CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode69:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ADC(Immediate());				CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode6A:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ROR_Accumulator();        		CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode6B:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ARR(Immediate());				CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode6C:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	JMP(Indirect());				CPU.CycleCount += 5;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode6D:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ADC(Absolute());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode6E:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ROR(Absolute());				CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode6F:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	RRA(Absolute());				CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode70:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	BVS(Relative());				CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode71:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ADC(Indirect_Indexed_Read());	CPU.CycleCount += 5;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode72:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	KIL();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode73:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	RRA(Indirect_Indexed());		CPU.CycleCount += 8;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode74:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode75:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ADC(Zero_Page_X());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode76:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ROR(Zero_Page_X());				CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode77:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	RRA(Zero_Page_X());				CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode78:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SEI();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode79:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ADC(Absolute_Y_Read());			CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode7A:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode7B:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	RRA(Absolute_Y());				CPU.CycleCount += 7;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode7C:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode7D:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ADC(Absolute_X_Read());			CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode7E:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ROR(Absolute_X());				CPU.CycleCount += 7;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode7F:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	RRA(Absolute_X());				CPU.CycleCount += 7;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode80:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode81:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	STA(Indexed_Indirect());		CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode82:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode83:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SAX(Indexed_Indirect());		CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode84:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	STY(Zero_Page());				CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode85:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	STA(Zero_Page());				CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode86:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	STX(Zero_Page());				CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode87:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SAX(Zero_Page());				CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode88:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	DEY();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode89:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode8A:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	TXA();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode8B:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	XAA(Immediate());				CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode8C:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	STY(Absolute());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode8D:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	STA(Absolute());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode8E:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	STX(Absolute());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode8F:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SAX(Absolute());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode90:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	BCC(Relative());				CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode91:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	STA(Indirect_Indexed());		CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode92:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	KIL();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode93:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	AHX(Indirect_Indexed());		CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode94:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	STY(Zero_Page_X());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode95:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	STA(Zero_Page_X());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode96:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	STX(Zero_Page_Y());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode97:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SAX(Zero_Page_Y());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	Opcode98:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	TYA();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode99:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	STA(Absolute_Y());				CPU.CycleCount += 5;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode9A:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	TXS();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	Opcode9B:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	TAS(Absolute_Y());				CPU.CycleCount += 5;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode9C:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SHY(Absolute_X());				CPU.CycleCount += 5;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode9D:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	STA(Absolute_X());				CPU.CycleCount += 5;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode9E:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SHX(Absolute_Y());				CPU.CycleCount += 5;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	Opcode9F:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	AHX(Absolute_Y());				CPU.CycleCount += 5;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeA0:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LDY(Immediate());				CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeA1:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LDA(Indexed_Indirect());		CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeA2:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LDX(Immediate());				CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeA3:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LAX(Indexed_Indirect());		CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeA4:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LDY(Zero_Page());				CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeA5:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LDA(Zero_Page());				CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeA6:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LDX(Zero_Page());				CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeA7:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LAX(Zero_Page());				CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeA8:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	TAY();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	OpcodeA9:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LDA(Immediate());				CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeAA:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	TAX();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	OpcodeAB:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LAX(Immediate());				CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeAC:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LDY(Absolute());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeAD:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LDA(Absolute());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeAE:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LDX(Absolute());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeAF:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LAX(Absolute());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeB0:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	BCS(Relative());				CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeB1:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LDA(Indirect_Indexed_Read());	CPU.CycleCount += 5;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeB2:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	KIL();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	OpcodeB3:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LAX(Indirect_Indexed());		CPU.CycleCount += 5;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeB4:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LDY(Zero_Page_X());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeB5:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LDA(Zero_Page_X());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeB6:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LDX(Zero_Page_Y());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeB7:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LAX(Zero_Page_Y());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeB8:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	CLV();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	OpcodeB9:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LDA(Absolute_Y_Read());			CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeBA:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	TSX();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	OpcodeBB:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LAS(Absolute_Y());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeBC:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LDY(Absolute_X_Read());			CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeBD:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LDA(Absolute_X_Read());			CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeBE:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LDX(Absolute_Y_Read());			CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeBF:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	LAX(Absolute_Y());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeC0:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	CPY(Immediate());				CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeC1:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	CMP(Indexed_Indirect());		CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeC2:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeC3:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	DCP(Indexed_Indirect());		CPU.CycleCount += 8;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeC4:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	CPY(Zero_Page());				CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeC5:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	CMP(Zero_Page());				CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeC6:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	DEC(Zero_Page());				CPU.CycleCount += 5;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeC7:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	DCP(Zero_Page());				CPU.CycleCount += 5;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeC8:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	INY();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	OpcodeC9:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	CMP(Immediate());				CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeCA:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	DEX();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	OpcodeCB:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	AXS(Immediate());				CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeCC:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	CPY(Absolute());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeCD:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	CMP(Absolute());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeCE:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	DEC(Absolute());				CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeCF:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	DCP(Absolute());				CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeD0:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	BNE(Relative());				CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeD1:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	CMP(Indirect_Indexed_Read());	CPU.CycleCount += 5;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeD2:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	KIL();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	OpcodeD3:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	DCP(Indirect_Indexed());		CPU.CycleCount += 8;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeD4:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeD5:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	CMP(Zero_Page_X());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeD6:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	DEC(Zero_Page_X());				CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeD7:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	DCP(Zero_Page_X());				CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeD8:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	CLD();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	OpcodeD9:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	CMP(Absolute_Y_Read());			CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeDA:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	OpcodeDB:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	DCP(Absolute_Y());				CPU.CycleCount += 7;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeDC:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeDD:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	CMP(Absolute_X_Read());			CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeDE:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	DEC(Absolute_X());				CPU.CycleCount += 7;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeDF:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	DCP(Absolute_X());				CPU.CycleCount += 7;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeE0:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	CPX(Immediate());				CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeE1:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SBC(Indexed_Indirect());		CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeE2:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeE3:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ISC(Indexed_Indirect());		CPU.CycleCount += 8;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeE4:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	CPX(Zero_Page());				CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeE5:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SBC(Zero_Page());				CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeE6:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	INC(Zero_Page());				CPU.CycleCount += 5;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeE7:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ISC(Zero_Page());				CPU.CycleCount += 5;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeE8:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	INX();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	OpcodeE9:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SBC(Immediate());				CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeEA:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	OpcodeEB:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SBC(Immediate());				CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeEC:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	CPX(Absolute());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeED:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SBC(Absolute());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeEE:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	INC(Absolute());				CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeEF:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ISC(Absolute());				CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeF0:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	BEQ(Relative());				CPU.CycleCount += 3;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeF1:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SBC(Indirect_Indexed_Read());	CPU.CycleCount += 5;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeF2:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	KIL();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	OpcodeF3:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ISC(Indirect_Indexed());		CPU.CycleCount += 8;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeF4:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeF5:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SBC(Zero_Page_X());				CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeF6:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	INC(Zero_Page_X());				CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeF7:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ISC(Zero_Page_X());				CPU.CycleCount += 6;	goto *Opcode[Memory_CPU_Read(CPU.PC += 2)];
	OpcodeF8:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SED();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	OpcodeF9:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SBC(Absolute_Y_Read());			CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeFA:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 2;	goto *Opcode[Memory_CPU_Read(CPU.PC += 1)];
	OpcodeFB:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ISC(Absolute_Y());				CPU.CycleCount += 7;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeFC:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	NOP();							CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeFD:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	SBC(Absolute_X_Read());			CPU.CycleCount += 4;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeFE:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	INC(Absolute_X());				CPU.CycleCount += 7;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];
	OpcodeFF:	if (CPU.CycleCount >= CPU.TargetCycle) { goto Interrupt };	ISC(Absolute_X());				CPU.CycleCount += 7;	goto *Opcode[Memory_CPU_Read(CPU.PC += 3)];

	Interrupt:  NMI(); CPU.CycleCount += 7;
}
